---
.travis.yml:
  forge_password: "r/FiALWC6liW5HiUIESpJT8IM+iWqDu8Cc9yXaU1k+9ZxGzjsB4+pQgTZ+H3sI19xU4LAUC6VOavG+aRK+U9LlCWY/6LhzJ53yIGalXqwoSS4zTglolxf1hvMcejp4S8wnFPKpzCD6vfRgppL/HqPSZ5CGM1/kaCp5Z9MT4DO1k="
