---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
after_success:
  ["git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng", ".forge-releng/publish"]
env:
  global:
    - PUBLISHER_LOGIN=camptocamp
    - secure: "ENkpHtG0v+r0QSiOF3+JdACwbqR0c1oLhbvoY4VGNh1blJtBRlTEyBcBjNGwfQdG3Ww9MjBKhHlBLRS8S3KXelczf9ooTCcFNDWv5ctJ1Uqerjd+/xHO2Ro/4iv8PvzmLViN1nVbR17SAqM2z66rlSckJS/h0b+AlZyTPui+GUo="
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
notifications:
  email: false
